### ISSUE TITLE
Can't use luau with laterst stable bms version

### ISSUE THREAD

**Issue by KevinGuancheDarias** [makspll/bevy_mod_scripting#415]
## Summary
Can't use luau

## Reproducing
Just add the dependency to the Cargo.toml and try to compile

```toml
bevy = { version = "0.15.3", features = ["wayland"] }
bevy_mod_scripting = { version = "0.11", default-features = false, features = ["luau"] }
```

Then after clicking build mlua-sys 0.6.7 would report error `You can enable only one of the features: lua54, lua53, lua52, lua51, luajit, luajit52, luau`

This error doesn't happen if I configure BMS to use lua54

Thanks for the great mod!
